blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('news', 'NewsController');

Route::resource('categories', 'CategoriesController');

Route::resource('comments', 'CommentsController');

Route::post('test', 'NewsController@test');

blog/app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\NewsRequest;
use App\NewsItem;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

class NewsController extends Controller {

	public function __construct() {
		//$this->middleware('admin')->except(['index', 'show']);
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index(Request $request) {
		//
		$page = $request->input( 'page', '1' );
		$news = Cache::remember( 'news_index_page_' . $page, 60, function () {
			return NewsItem::orderBy( 'created_at', 'DESC' )->with( 'user' )->paginate( 50 );
		});



		return view( 'news.index', [ 'news' => $news] );

	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//

		$categories = Category::topLevelCategories()->get();

		return view( 'news.create', [
			"categories" => $categories
		] );
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( NewsRequest $request ) {
		//
		$newsItem          = new NewsItem();
		$newsItem->title   = $request->input( 'title' );
		$newsItem->content = $request->input( 'content' );
		$newsItem->user_id = Auth::user()->id;
//		$newsItem->language = App::getLocale();

		if ( $request->has( 'image' ) ) {
			$imagePath       = $request->file( 'image' )->store( 'news-images' );
			$newsItem->image = $imagePath;
		}

		$newsItem->save();

		$newCategories = $request->input( 'categories' );
		$newsItem->categories()->sync( $newCategories );


		return redirect()->route( 'news.index' );
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show( $id ) {
		//

		$item = NewsItem::with( [ 'topLevelComments', 'user', 'categories' ] )->find( $id );


		return view( 'news.show', [ 'item' => $item ] );
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {
		//

		$newsItem   = NewsItem::find( $id );
		$categories = Category::all();

		return view( 'news.edit', [ 'newsItem' => $newsItem, 'categories' => $categories ] );
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( Request $request, $id ) {
		//
		$newsItem          = NewsItem::find( $id );
		$newsItem->title   = $request->input( 'title' );
		$newsItem->content = $request->input( 'content' );


		if ( $request->has( 'image' ) ) {
			$imagePath       = $request->file( 'image' )->store( 'news-images' );
			$newsItem->image = $imagePath;
		}

		$newCategories = $request->input( 'categories' );
		$newsItem->categories()->sync( $newCategories );

		$newsItem->save();

		return redirect()->back();
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id ) {
		//
	}
}

blog/resources/views/news/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form method="post" action="{{ route('news.store') }}" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <h1>Create news item</h1>

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @csrf

                    @method('post')

                    <div class="form-group">
                        <input type="text" name="title" placeholder="Title" required class="form-control"
                               value="{{ old('title') }}">
                    </div>

                    <div class="form-group">
                        <textarea name="content">{{ old('content') }}</textarea>
                    </div>

                    <div class="form-group">
                        <label>Image</label>
                        <input type="file" name="image" class="form-control">
                    </div>

                    <input type="submit" value="Save" class="btn btn-success">


                </div>
                <div class="col-md-6">

                    @foreach($categories as $category)
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="categories[]"
                                   value="{{ $category->id }}">
                            <label class="form-check-label">{{ $category->title }}</label>
                        </div>
                        <div class="sub-categories pl-3">
                            @foreach($category->subCategories as $subCategory)
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="categories[]"
                                           value="{{ $subCategory->id }}">
                                    <label class="form-check-label"> {{ $subCategory->title }}</label>
                                </div>

                            @endforeach
                        </div>
                    @endforeach


                </div>
            </div>
        </form>

    </div>
@endsection

blog/resources/views/news/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form method="post" action="{{ route('news.update', [$newsItem->id]) }}" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <h1>Edit news item: {{ $newsItem->title }}</h1>

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @csrf

                    @method('put')

                    <div class="form-group">
                        <input type="text" name="title" placeholder="Title" required class="form-control"
                               value="{{ $newsItem->title }}">
                    </div>

                    <div class="form-group">
                        <textarea name="content" class="form-control"
                                  placeholder="Enter content here">{{ $newsItem->content }}</textarea>
                    </div>

                    <div class="form-group">
                        <label>Image</label>
                        <input type="file" name="image" class="form-control">
                    </div>

                    <input type="submit" value="Save" class="btn btn-success">


                </div>
                <div class="col-md-6">

                    @foreach($categories as $category)
                        <div class="form-check">


                            <input class="form-check-input" type="checkbox" name="categories[]"
                            @foreach($newsItem->categories as $cat)
                                @if($cat->id == $category->id)
                                    checked
                                    @break
                                @endif
                            @endforeach
                                   value="{{ $category->id }}">
                            <label class="form-check-label">{{ $category->title }}</label>
                        </div>
                    @endforeach


                </div>
            </div>
        </form>

    </div>
@endsection

blog/resources/views/news/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @foreach($news as $item)
                @include('components.news-item')
            @endforeach

            <div>
                {{ $news->links() }}
            </div>
        </div>
    </div>
@endsection

blog/resources/views/news/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>{{ $item->title }}</h1>
                <p>
                    {!!  $item->content !!}
                </p>

                <div class="comments">
                    @include('components.comment-form')
                </div>

                <div class="display-comments">
                    @include('components.display-comments')
                </div>
            </div>

            <div class="col-md-4">
                <h3>
                    Kategorijos
                </h3>
                <ul>
                    @foreach($item->categories as $category)
                        <li>{{ $category->title }}</li>
                    @endforeach
                </ul>

            </div>
        </div>

    </div>
@endsection